# Generated by Django 5.0.4 on 2024-05-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_usermanage_user_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermanage',
            options={},
        ),
        migrations.AlterModelManagers(
            name='usermanage',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='is_studio_owner',
        ),
        migrations.RemoveField(
            model_name='usermanage',
            name='last_name',
        ),
        migrations.AddField(
            model_name='usermanage',
            name='user_type',
            field=models.CharField(choices=[('studio_owner', 'Studio Owner'), ('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usermanage',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
