# Generated by Django 5.0.4 on 2024-05-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_usermanage_options_alter_usermanage_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermanage',
            name='is_studio_owner',
            field=models.BooleanField(default=False),
        ),
    ]
