# Generated by Django 5.0.4 on 2024-05-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_cancelled',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reserved_date',
            field=models.CharField(default=['13-05-2024'], max_length=255),
            preserve_default=False,
        ),
    ]
