# Generated by Django 5.0.4 on 2024-05-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_remove_reservation_is_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_date',
            field=models.DateField(),
        ),
    ]
