# Generated by Django 5.0.4 on 2024-05-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_alter_reservation_reserved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reserved_date',
            field=models.JSONField(default=list),
        ),
    ]
