# Generated by Django 5.0.4 on 2024-05-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='reservations',
            field=models.JSONField(default=list),
        ),
    ]
