# Generated by Django 5.0.4 on 2024-05-11 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_studio_reservations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
